### ISSUE TITLE
给纪委投票时post出错,返回"请登录"

### ISSUE THREAD

**Issue by mzz2017** [Actooors/vote_tool#6]
#### 纪委投票:
`http://localhost:8081/api/vote/groupPullVote`
会
```javascript
{"code":"FAILED","message":"请登录","data":null}
```

#### 但是党委投票:
`http://localhost:8081/api/vote/partyPullVote`
就是
```javascript
{"code":"SUCCESS","message":null,"data":null}
```
没有问题.

注: 我没连校园网, 但为什么会在这里提示我没有登录??

**Comment by 0GGmr0** [comment]
bug调试完成
